### ISSUE TITLE
NEW **gif** avatars are not loading to poker-heroes

### ISSUE THREAD

**Issue by JroJsh** [pokerth/pokerth#295] opened 2015-04-29 09:03 UTC
the "gif" avatars we have now work, but if we update to newer "gif" avatar it doesn't do it right.  we get the avatar showing up locally so we can see it but nobody else at table does... and our stats page on poker heroes doesnt show new "gif" avatar either, just a blank.  if we put our old avatar back it works everywhere as it should.  new "gif" avatars   are not working...the page code must be off or wrong...

**edit** added "gif" as it was determined not to effect png or jpg now...

**Comment by lotodore** [comment] 2015-06-27 20:22
Sorry that this takes so long to fix, but this needs a coordinated reset between the PokerTH server and poker heroes. We do not want to shut down the server for too long, which is why we are delaying this until we find a coordinated time. Anyway, this is not a bug in the code, it is a problem with avatar storage.

**Comment by lotodore** [comment] 2016-02-01 22:07
This should be fixed now. If it does not work, please report in the pokerth forum or to poker-heroes, as this is an operations issue and no issue in the code.

**Closed by lotodore** 2016-02-01 22:07 UTC
