### ISSUE TITLE
Show name of winning hand

### ISSUE THREAD

**Issue by kingofthejambo** [pokerth/pokerth#309] opened 2016-05-15 12:55 UTC
Please show the name of the winning hand after a player has won

**Comment by Rbagman** [comment] 2016-05-16 00:52
The winner name is in the log.

**Comment by porjo** [comment] 2017-12-29 04:45
Duplicate of #306

**Comment by andy5995** [comment] 2022-01-03 20:54
> Duplicate of #306

Can this be closed now?

**Closed** 2022-01-03 22:26 UTC
