### ISSUE TITLE
Database interface, crashed on user authentication

### ISSUE THREAD

**Issue by sefgit** [pokerth/pokerth#281] opened 2014-07-01 09:05 UTC
Trying to understand how to integrate database for user authentication, I manually changed  the *POKERTH_OFFICIAL_SERVER* (as needed) to activate database callback.
After some frustrated trial and errors with many pokerth_server crashes under linux, I decided to modify following callback interface:
* virtual void PlayerLoginSuccess(unsigned requestId, const boost::shared_ptr<DBPlayerData> &dbPlayerData);
* void UserValid(unsigned playerId, const boost::shared_ptr<DBPlayerData> &dbPlayerData);

Attached is a patch for PokerTH-1.1.1-src.tar.bz2 to experiment with.
Note: as you can see in the patch, for any login name, the "login password" is: 1234

Disclaimer:
Please verify that no memory leak is happening with this interface modification. 

	diff -wEruN PokerTH-1.1.1-src/src/db/common/serverdbgeneric.cpp PokerTH-1.1.1-patched/src/db/common/serverdbgeneric.cpp
	--- PokerTH-1.1.1-src/src/db/common/serverdbgeneric.cpp	2014-01-11 04:18:20.762643128 +0700
	+++ PokerTH-1.1.1-patched/src/db/common/serverdbgeneric.cpp	2014-07-01 15:15:12.925606792 +0700
	@@ -63,13 +63,22 @@
	 void
	 ServerDBGeneric::AsyncPlayerLogin(unsigned requestId, const string &/*playerName*/)
	 {
	-	m_ioService->post(boost::bind(&ServerDBCallback::PlayerLoginFailed, &m_callback, requestId));
	+	//m_ioService->post(boost::bind(&ServerDBCallback::PlayerLoginFailed, &m_callback, requestId));
	+
	+	// test data, probably from database
	+	boost::shared_ptr<DBPlayerData> dbPlayerData(new DBPlayerData());
	+	dbPlayerData->id = 1;
	+	dbPlayerData->secret = "1234";
	+	dbPlayerData->country = "id";
	+	dbPlayerData->last_login = "";
	+	m_ioService->post(boost::bind(&ServerDBCallback::PlayerLoginSuccess, &m_callback, requestId, dbPlayerData));
	 }
	 
	 void
	 ServerDBGeneric::AsyncCheckAvatarBlacklist(unsigned requestId, const std::string &/*avatarHash*/)
	 {
	-	m_ioService->post(boost::bind(&ServerDBCallback::AvatarIsBlacklisted, &m_callback, requestId));
	+	//m_ioService->post(boost::bind(&ServerDBCallback::AvatarIsBlacklisted, &m_callback, requestId));
	+	m_ioService->post(boost::bind(&ServerDBCallback::AvatarIsOK, &m_callback, requestId));
	 }
	 
	 void
	@@ -85,7 +94,8 @@
	 void
	 ServerDBGeneric::AsyncCreateGame(unsigned requestId, const string &/*gameName*/)
	 {
	-	m_ioService->post(boost::bind(&ServerDBCallback::CreateGameFailed, &m_callback, requestId));
	+	//m_ioService->post(boost::bind(&ServerDBCallback::CreateGameFailed, &m_callback, requestId));
	+	m_ioService->post(boost::bind(&ServerDBCallback::CreateGameSuccess, &m_callback, requestId));
	 }
	 
	 void
	@@ -101,13 +111,15 @@
	 void
	 ServerDBGeneric::AsyncReportAvatar(unsigned requestId, unsigned replyId, DB_id /*reportedPlayerId*/, const std::string &/*avatarHash*/, const std::string &/*avatarType*/, DB_id * /*byPlayerId*/)
	 {
	-	m_ioService->post(boost::bind(&ServerDBCallback::ReportAvatarFailed, &m_callback, requestId, replyId));
	+	//m_ioService->post(boost::bind(&ServerDBCallback::ReportAvatarFailed, &m_callback, requestId, replyId));
	+	m_ioService->post(boost::bind(&ServerDBCallback::ReportAvatarSuccess, &m_callback, requestId, replyId));
	 }
	 
	 void
	 ServerDBGeneric::AsyncReportGame(unsigned requestId, unsigned replyId, DB_id * /*creatorPlayerId*/, unsigned /*gameId*/, const std::string &/*gameName*/, DB_id * /*byPlayerId*/)
	 {
	-	m_ioService->post(boost::bind(&ServerDBCallback::ReportGameFailed, &m_callback, requestId, replyId));
	+	//m_ioService->post(boost::bind(&ServerDBCallback::ReportGameFailed, &m_callback, requestId, replyId));
	+	m_ioService->post(boost::bind(&ServerDBCallback::ReportGameSuccess, &m_callback, requestId, replyId));
	 }
	 
	 void
	@@ -116,7 +128,9 @@
	 }
	 
	 void
	-ServerDBGeneric::AsyncBlockPlayer(unsigned /*requestId*/, unsigned /*replyId*/, DB_id /*playerId*/, int /*valid*/, int /*active*/)
	+ServerDBGeneric::AsyncBlockPlayer(unsigned requestId, unsigned replyId, DB_id /*playerId*/, int /*valid*/, int /*active*/)
	 {
	+	//m_ioService->post(boost::bind(&ServerDBCallback::BlockPlayerFailed, &m_callback, requestId, replyId));
	+	m_ioService->post(boost::bind(&ServerDBCallback::BlockPlayerSuccess, &m_callback, requestId, replyId));
	 }
	 
	diff -wEruN PokerTH-1.1.1-src/src/db/serverdbcallback.h PokerTH-1.1.1-patched/src/db/serverdbcallback.h
	--- PokerTH-1.1.1-src/src/db/serverdbcallback.h	2014-01-11 04:18:20.763643127 +0700
	+++ PokerTH-1.1.1-patched/src/db/serverdbcallback.h	2014-07-01 15:15:12.925606792 +0700
	@@ -50,7 +50,7 @@
	 
		virtual void QueryError(std::string error) = 0;
	 
	-	virtual void PlayerLoginSuccess(unsigned requestId, boost::shared_ptr<DBPlayerData> dbPlayerData) = 0;
	+	virtual void PlayerLoginSuccess(unsigned requestId, const boost::shared_ptr<DBPlayerData> &dbPlayerData) = 0;
		virtual void PlayerLoginFailed(unsigned requestId) = 0;
		virtual void PlayerLoginBlocked(unsigned requestId) = 0;
	 
	diff -wEruN PokerTH-1.1.1-src/src/net/common/servergame.cpp PokerTH-1.1.1-patched/src/net/common/servergame.cpp
	--- PokerTH-1.1.1-src/src/net/common/servergame.cpp	2014-01-11 04:18:20.919643110 +0700
	+++ PokerTH-1.1.1-patched/src/net/common/servergame.cpp	2014-07-01 15:15:12.925606792 +0700
	@@ -292,10 +292,10 @@
	 
		if (playerData.size() >= 2) {
			// Set DB Backend.
	-		if (GetGameData().gameType == GAME_TYPE_RANKING)
	+//		if (GetGameData().gameType == GAME_TYPE_RANKING)
				m_database = GetLobbyThread().GetDatabase();
	-		else
	-			m_database.reset(new ServerDBNoAction);
	+//		else
	+//			m_database.reset(new ServerDBNoAction);
	 
			// Randomize player list.
			// Note: This does not use a cryptographically strong
	diff -wEruN PokerTH-1.1.1-src/src/net/common/serverlobbythread.cpp PokerTH-1.1.1-patched/src/net/common/serverlobbythread.cpp
	--- PokerTH-1.1.1-src/src/net/common/serverlobbythread.cpp	2014-01-11 04:18:20.920643110 +0700
	+++ PokerTH-1.1.1-patched/src/net/common/serverlobbythread.cpp	2014-07-01 15:15:12.929606823 +0700
	@@ -154,8 +154,8 @@
			LOG_ERROR("DB query error: " << error);
		}
	 
	-	virtual void PlayerLoginSuccess(unsigned requestId, boost::shared_ptr<DBPlayerData> dbPlayerData) {
	-		m_server.UserValid(requestId, *dbPlayerData);
	+	virtual void PlayerLoginSuccess(unsigned requestId, const boost::shared_ptr<DBPlayerData> &dbPlayerData) {
	+		m_server.UserValid(requestId, dbPlayerData);
		}
	 
		virtual void PlayerLoginFailed(unsigned requestId) {
	@@ -1063,7 +1063,7 @@
				return;
			}
		}
	-#ifdef POKERTH_OFFICIAL_SERVER
	+#ifndef POKERTH_OFFICIAL_SERVER
		else if (initMessage.login() == InitMessage::authenticatedLogin) {
			string inAuthData(initMessage.clientuserdata());
			if (initMessage.has_avatarhash()) {
	@@ -1749,13 +1749,13 @@
	 }
	 
	 void
	-ServerLobbyThread::UserValid(unsigned playerId, const DBPlayerData &dbPlayerData)
	+ServerLobbyThread::UserValid(unsigned playerId, const boost::shared_ptr<DBPlayerData> &dbPlayerData)
	 {
		boost::shared_ptr<SessionData> tmpSession = m_sessionManager.GetSessionByUniquePlayerId(playerId, true);
		if (tmpSession && tmpSession->GetPlayerData()) {
	-		tmpSession->GetPlayerData()->SetDBId(dbPlayerData.id);
	-		tmpSession->GetPlayerData()->SetCountry(dbPlayerData.country);
	-		this->AuthChallenge(tmpSession, dbPlayerData.secret);
	+		tmpSession->GetPlayerData()->SetDBId(dbPlayerData->id);
	+		tmpSession->GetPlayerData()->SetCountry(dbPlayerData->country);
	+		this->AuthChallenge(tmpSession, dbPlayerData->secret);
		}
	 }
	 
	diff -wEruN PokerTH-1.1.1-src/src/net/serverlobbythread.h PokerTH-1.1.1-patched/src/net/serverlobbythread.h
	--- PokerTH-1.1.1-src/src/net/serverlobbythread.h	2014-01-11 04:18:20.924643110 +0700
	+++ PokerTH-1.1.1-patched/src/net/serverlobbythread.h	2014-07-01 15:15:12.929606823 +0700
	@@ -173,7 +173,7 @@
		void InitAfterLogin(boost::shared_ptr<SessionData> session);
		void EstablishSession(boost::shared_ptr<SessionData> session);
		void AuthenticatePlayer(boost::shared_ptr<SessionData> session);
	-	void UserValid(unsigned playerId, const DBPlayerData &dbPlayerData);
	+	void UserValid(unsigned playerId, const boost::shared_ptr<DBPlayerData> &dbPlayerData);
		void UserInvalid(unsigned playerId);
		void UserBlocked(unsigned playerId);
	 
	diff -wEruN PokerTH-1.1.1-src/src/session.cpp PokerTH-1.1.1-patched/src/session.cpp
	--- PokerTH-1.1.1-src/src/session.cpp	2014-01-11 04:18:20.926643109 +0700
	+++ PokerTH-1.1.1-patched/src/session.cpp	2014-07-01 15:15:12.929606823 +0700
	@@ -319,7 +319,7 @@
	 
		ServerMode mode;
		if (dedicated) {
	-#ifdef POKERTH_OFFICIAL_SERVER
	+#ifndef POKERTH_OFFICIAL_SERVER
			mode = SERVER_MODE_INTERNET_AUTH;
	 #else
			mode = SERVER_MODE_INTERNET_NOAUTH;

**Comment by lotodore** [comment] 2015-01-06 13:19
This is an informational patch, and there have been no more comments, so I'm closing it (as it is not a bug).

**Closed by lotodore** 2015-01-06 13:19 UTC
